## Introduction to Tensors

### Creating tensors with `tf.constant()`

In [1]:
# Import tensorflow

import tensorflow as tf

print(tf.__version__)

2.7.0


In [ ]:
# create a tensor with tf.constant()

scalar = tf.constant(7)

In [ ]:
dimension_of_scalar = scalar.ndim
print(f"dimension of scalar is {dimension_of_scalar}")

dimension of scalar is 0


In [5]:
# crate a vector ( with dimension 1)

vector = tf.constant([2,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [6]:
dimension_of_vector = vector.ndim
print(f"dimension of vector is {dimension_of_vector}")

dimension of vector is 1


In [7]:
# create a matrix 

matrix = tf.constant([
                      [2,4],
                      [4,2]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [4, 2]], dtype=int32)>

In [8]:
dimension_of_matrix = matrix.ndim
print(f"dimension of matrix is {dimension_of_matrix}")

dimension of matrix is 2


In [14]:
# we can also specify the data type while creating a tensor
another_matrix = tf.constant([
                              [1,2],
                              [3,4],
                              [5,6]
],dtype=tf.float16,shape=[2,3])
another_matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>

### Creating tensors with `tf.Variable()`

In [17]:
changeable_vector = tf.Variable([5,6])
unchangeable_vector = tf.constant([5,6])
changeable_vector, unchangeable_vector

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 6], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>)

but we can't change or assign the element of a changeable vector or tensor with assignment operator `=`

In [18]:
changeable_vector[1]

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [19]:
changeable_vector[1] = 12

TypeError: ignored

rathar , we can assign or change it via `tensor.assign()` method

In [23]:
changeable_vector[1].assign(12)
changeable_vector, changeable_vector[1]

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 5, 12], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>)

but , changing the elements of a unchangeable_vector or constant is not possible and thats why it is called constant

In [22]:
unchangeable_vector[1]

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [24]:
unchangeable_vector[1].assign(12)

AttributeError: ignored

### Creating random tensors 

In [25]:
# specifying random seed 

random_1 = tf.random.Generator.from_seed(24)


In [26]:
random_1 = random_1.normal(shape = [3,2])
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.10944034, -0.8035768 ],
       [-1.7166729 ,  0.3738578 ],
       [-0.14371012, -0.34646833]], dtype=float32)>

In [28]:
random_2 = tf.random.Generator.from_seed(24)

random_2 = random_2.normal(shape = [3,2])

random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [29]:
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.10944034, -0.8035768 ],
        [-1.7166729 ,  0.3738578 ],
        [-0.14371012, -0.34646833]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.10944034, -0.8035768 ],
        [-1.7166729 ,  0.3738578 ],
        [-0.14371012, -0.34646833]], dtype=float32)>)

each time we create tensor with same seed , the element of the tensors will be the same as the seed is the same . But, if the seed differs , the element will also get changed 

In [30]:
random_3 = tf.random.Generator.from_seed(33)
random_3 = random_3.normal(shape = [3,2])

random_4 = tf.random.Generator.from_seed(32)
random_4 = random_4.normal(shape = [3,2])

random_3 == random_4

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [31]:
random_3, random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.1589871 ,  1.302304  ],
        [ 0.9592239 ,  0.85874265],
        [-1.5181769 ,  1.4020647 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182 ,  1.585549  ],
        [ 0.4356279 ,  0.23645182],
        [-0.1589871 ,  1.302304  ]], dtype=float32)>)

## Shuffling the order of a tensor

### Why do we need to shuffle the order ?

take an example of 100 image classification. If there is a scenario, where all the first 60 images are of dogs and the rest 40 images are of cats, our model may get confused here. Because, as it starts to learn, it will learn only one pattern first, so, it might get difficult for the model to learn the difference between those two. For minimizing that problem or we can say, add versatility to our data set, we need to shuffle the order of our data set.

In [35]:
 # creat a tensor 

 not_shuffled = tf.constant([
                             [1,2],
                             [10,7],
                             [14,12]
 ])

 tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[14, 12],
       [ 1,  2],
       [10,  7]], dtype=int32)>

In [37]:
 tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [14, 12],
       [10,  7]], dtype=int32)>

In [54]:
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [10,  7],
       [14, 12]], dtype=int32)>

In [55]:
tf.random.set_seed(42) # setting global seed 
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [14, 12],
       [ 1,  2]], dtype=int32)>

In [67]:
tf.random.set_seed(42) # global seed declartion

tf.random.shuffle(not_shuffled, seed = 42) # operational seed declartion

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [10,  7],
       [14, 12]], dtype=int32)>